const img='/widgets/demo/';
const demo='演示素材 / 非 NKU 实验结果';
const entry=(id,title,groups,tip,blocks)=>({id,title,groups,tip,blocks});
const b=(type,props)=>({_template:type,...props});
const layout=(kind,body,props={})=>b('layout',{kind,body,...props});
const series='Time,Control,Design A,Design B\n'+Array.from({length:15},(_,i)=>`${i},${(i*.22).toFixed(2)},${(8*(1-Math.exp(-i/5))).toFixed(2)},${(6*(1-Math.exp(-i/3))).toFixed(2)}`).join('\n');
export const showcase=[
entry('01','工程循环分栏',['湿实验','干实验'],'点击四个阶段切换；适合讲清一轮工程循环。',[b('tabs',{title:'Cycle 02 · Design → Build → Test → Learn',items:[{title:'Design 设计',text:'问题：如何比较多个候选方案？\n假设：统一输入条件后，不同方案将表现出不同响应曲线。\n交付：比较矩阵、评价指标、下一步计划。'},{title:'Build 构建',text:'展示构建设计、版本记录和关键选择。\n可在后续模块插入结构模型、序列和设计文件。\n此处仅为页面组织示例。'},{title:'Test 评价',text:'整理对照条件、原始数据与重复记录。\n下方图表组件可以展示多组曲线。\n示例不构成实验方法或真实结果。'},{title:'Learn 迭代',text:'结论 → 证据 → 局限 → 下一轮改动。\n将反馈与设计决策对应，形成可追溯的迭代记录。'}],caption:demo})]),
entry('02','折叠访谈与问答',['HP','全组'],'逐条展开，保留较长访谈内容而不占满页面。',[b('accordion',{title:'Stakeholder interview · 访谈记录',items:[{title:'01 背景与需求',text:'角色：虚构的使用者 A。\n场景：希望快速找到页面中的核心结论。\n需求：先看到摘要，再按需展开证据。'},{title:'02 反馈如何影响设计？',text:'反馈：长篇内容不易浏览。\n改动：使用折叠问答、图片说明和下载附件。\n后续：记录是否满足使用者需要。'},{title:'03 如何展示引用与授权？',text:'填写实际访谈日期、公开范围、引用方式。\n示例中没有真实受访者或个人资料。'}],caption:demo})]),
entry('03','分类 Notebook 时间线',['湿实验','干实验','HP'],'试试切换组别；跨组事件按阶段展示。',[b('chronology',{title:'Project notebook · 跨组记录',items:Array.from({length:9},(_,i)=>({date:`2026 / ${String(i+1).padStart(2,'0')}`,category:['Wet Lab','Dry Lab','HP'][i%3],title:['需求与假设','方案比较','阶段复盘'][i%3]+` · ${i+1}`,text:'演示记录：本阶段输入 → 形成的材料 → 反馈 → 下一步调整。',href:'#sample-01'})),caption:demo})]),
entry('04','步骤与材料清单',['湿实验'],'勾选步骤查看完成数量；适合方法、流程和材料清单。',[b('protocol',{title:'文档交付检查流程',materials:'原始记录（示意）\n图片与图注\n版本说明\n参考资料',items:[{title:'整理材料',text:'按页面名称建立资料目录，保留原始文件。',duration:'阶段 1'},{title:'核对图文',text:'确认图片编号、单位和正文引用对应。',duration:'阶段 2'},{title:'补充来源',text:'在图注中填写来源和说明。',duration:'阶段 3'},{title:'提交排版',text:'附上最终文件和修改记录。',duration:'阶段 4'}],caption:'仅演示排版；勾选状态不保存为实验记录。'})]),
entry('05','相册与大图浏览',['HP','湿实验','设计'],'点击任意缩略图放大；适合活动记录和多张结果图。',[b('lightbox',{title:'Visual archive · 图像档案',items:Array.from({length:6},(_,i)=>({image:img+(i%2?'after.svg':'before.svg'),title:`Figure ${i+1} · 设计示意`,text:`图 ${i+1}：独立图注与来源说明。人工绘制的图形，用于展示相册交互。`})),caption:demo})]),
entry('06','双图滑动对比',['湿实验','干实验','设计'],'拖动分界；适合改版、处理前后或两个方案对照。',[b('comparison',{title:'Design A / Design B',before:img+'before.svg',after:img+'after.svg',beforeLabel:'方案 A',afterLabel:'方案 B',caption:demo})]),
entry('07','视频与字幕',['HP','湿实验','设计'],'原生播放器：播放、进度、音量、全屏；示例配 VTT 字幕。',[b('video',{title:'Video · 演示片段',file:img+'demo.mp4',poster:img+'before.svg',subtitles:img+'demo.vtt',language:'zh',caption:'3 秒纯色示例，用于演示播放控件，不是项目视频。'})]),
entry('08','文件下载集合',['全组'],'CSV、结构、PDF、HTML 均可放进同一下载区。',[b('downloads',{title:'Supplementary materials',items:[{title:'演示数据 CSV',file:img+'data.csv',text:'用于了解表格文件格式。'},{title:'公开示例结构 1CRN',file:img+'1crn.pdb',text:'来源 RCSB PDB；不是本项目结构。'},{title:'公开 PDF 示例',file:img+'reference.pdf',text:'Mozilla PDF.js 官方展示文档。'},{title:'交互 HTML 演示',file:img+'interactive.html',text:'自包含的图形演示页面。'}],caption:demo})]),
entry('09','大型数据表 / Parts 表',['湿实验','干实验'],'60 行、6 列：搜索、数字排序、翻页。',[b('datatable',{title:'Parts catalogue · 虚构条目',csv:'ID,Type,Length,Version,Status,Note\n'+Array.from({length:60},(_,i)=>`DEMO-${String(i+1).padStart(3,'0')},${['Promoter','CDS','Terminator'][i%3]},${120+i*37},v${i%4+1},${['Draft','Review','Ready'][i%3]},Synthetic display row`).join('\n'),caption:'全部 ID 和数字均为演示，不是 Registry 注册信息。'})]),
...['line','bar','scatter'].map((type,i)=>entry(String(10+i),['多系列折线图','分组柱状图','多系列散点图'][i],['干实验','湿实验'], '可点击图例隐藏系列、悬停查看数据、下载 PNG；下方附可筛选原始表。',[b('chart',{title:['Response curves','Design comparison','Data distribution'][i],chartType:type,csv:series,xLabel:'Time (arbitrary units)',yLabel:'Response (arbitrary units)',caption:'程序生成的演示数字；无拟合、误差棒或统计推断。'})])),
entry('13','序列检索与注释',['干实验','湿实验'],'长序列、分段高亮、查找和复制；展示 DNA 与蛋白两种。',[b('sequence',{title:'DNA sequence · 多区域高亮',sequenceType:'dna',sequence:'>SYNTHETIC_DEMO\n'+'ACGTGCAATCGATGCTAGCT'.repeat(24),highlight:'12-48,100-160,250-290',caption:demo}),b('sequence',{title:'Protein sequence · 字母与位置',sequenceType:'protein',sequence:'>SYNTHETIC_DEMO\n'+'ACDEFGHIKLMNPQRSTVWY'.repeat(8),highlight:'20-40,90-110',caption:'人工重复氨基酸序列，不对应真实蛋白。'})]),
entry('14','复杂公式排版',['干实验'],'多行方程、矩阵、求和与下标；支持无障碍 MathML。',[b('equation',{title:'Model notation',latex:String.raw`\begin{aligned}\frac{dS}{dt}&=u(t)-kS-\frac{V_{\max}S}{K_m+S}\\\mathbf y&=\begin{bmatrix}1&0\\0&\alpha\end{bmatrix}\mathbf x+\boldsymbol\epsilon\\\mathcal L(\theta)&=\sum_{i=1}^{n}\left(y_i-\hat y_i(\theta)\right)^2+\lambda\lVert\theta\rVert_2^2\end{aligned}`,caption:'通用数学排版示例，不是本项目模型或拟合结果。'})]),
entry('15','可旋转蛋白结构',['干实验','湿实验'],'拖动旋转、缩放；切换丝带/球棍/原子球/表面，自动旋转和复位。',[b('protein',{title:'Crambin · 1CRN',file:img+'1crn.pdb',format:'pdb',representation:'cartoon',color:'#8cae73',chain:'A',residues:'7-12,30-35',height:620,caption:'RCSB PDB 1CRN 公开结构；紫色区域仅演示选区，不代表功能位点。来源 https://www.rcsb.org/structure/1CRN'})]),
entry('16','浏览器原生 PDF',['全组'],'多页公开文档；具体缩略图、搜索、打印等功能随浏览器而异。',[b('pdf',{title:'PDF · 公开示例文档',file:img+'reference.pdf',height:720,caption:'来自 Mozilla PDF.js 官方示例的计算机论文，仅作阅读器展示，与本项目研究无关。'})]),
entry('17','HTML 交互阅读器',['干实验','HP','设计'],'拖动参数改变曲线，展示可嵌入的自包含小网页。',[b('html',{title:'Interactive explainer · 图形演示',file:img+'interactive.html',scripts:true,height:620,caption:'自制参数交互示例，隔离运行，不是科学模拟器。'})]),
entry('18','标题、富文本与表格',['全组'],'二至四级标题、强调、引用、列表、链接、代码和表格。',[b('heading',{level:2,text:'一段完整内容如何组织',attributes:'#example-heading notoc'}),b('text',{body:'正文可以包含 **粗体重点**、*强调文字*、[跳转到候选清单](#selection)、`行内代码`以及脚注式引用 [1]。\n\n### 小标题：证据与解释\n\n> 先讲清问题，再呈现证据，最后说明局限。\n\n1. 整理材料\n2. 选择模块\n3. 核对图文\n\n#### 数据摘要\n\n| 项目 | 方案 A | 方案 B |\n| :--- | ---: | ---: |\n| 演示指标 1 | 12 | 18 |\n| 演示指标 2 | 0.6 | 0.8 |\n\n```text\nSample → Record → Review → Publish\n```'})]),
entry('19','单图与图注',['全组'], '图片、图注和来源组合。',[b('image',{src:img+'before.svg',alt:'人工绘制的几何示意图',body:'**Fig. 1** 图形示例。图注解释读图方式、来源及限制。'})]),
entry('20','双图并排',['湿实验','HP','设计'],'两张图分别说明，底部可放统一图注。',[b('gallery',{left:img+'before.svg',leftAlt:'A · 初始设计',right:img+'after.svg',rightAlt:'B · 修订设计',body:'**Fig. 2** 两种图形方案，仅作排版演示。'})]),
...['note','tip','warning'].map((kind,i)=>entry(String(21+i),['说明提示框','建议提示框','注意提示框'][i],['全组'],'标题、正文、强调和列表组合。',[layout(kind,'这是一段 **可强调的提示内容**。\n\n- 说明结论适用范围\n- 补充文件来源\n- 指出仍需补充的材料',{label:['说明','阅读建议','演示内容提示'][i]})])),
entry('24','四列入口卡片',['全组'],'四个带链接的内容入口；小屏自动换行。',[layout('cards', ['Design','Build','Test','Learn'].map((name,i)=>`### ${name} {href="#sample-01"}\n\n第 ${i+1} 个阶段的摘要和材料入口。`).join('\n\n'),{attributes:'cols="4"'})]),
entry('25','无边框多列排版',['全组'],'同一行并列讲三个主题。',[layout('cols','### 背景\n\n当前问题与目标。\n\n### 方法\n\n输入材料与设计思路。\n\n### 讨论\n\n局限与下一步方向。',{attributes:'cols="3"'})]),
entry('26','经典时间线',['HP','湿实验'],'静态时间线，支持富文本和链接。',[layout('timeline','### 探索 {when="阶段 01"}\n\n提出问题并整理资料。\n\n### 设计 {when="阶段 02"}\n\n比较方案，记录选择依据。\n\n### 复盘 {when="阶段 03"}\n\n汇总反馈，规划下一轮。')]),
entry('27','编号特性列表',['全组'],'有序要点与跳转箭头。',[layout('features','### 易于阅读 {idx="01" href="#sample-18"}\n\n通过清晰标题和摘要建立阅读顺序。\n\n### 按需展开 {idx="02" href="#sample-02"}\n\n长内容放入折叠区。\n\n### 可追溯 {idx="03" href="#sample-08"}\n\n提供原始附件和来源。')]),
entry('28','指标卡片',['HP','湿实验','干实验'],'适合关键数字摘要，请始终注明指标含义与来源。',[layout('stats','### 24\n\n演示条目数量\n\n### 3\n\n演示分组\n\n### 82%\n\n虚构比例\n\n### 7 days\n\n示例时间跨度')]),
entry('29','参考文献',['全组'],'自动编号的来源列表。',[layout('refs','1. RCSB PDB. [1CRN 结构条目](https://www.rcsb.org/structure/1CRN). 本页结构示例来源。\n2. Mozilla. [PDF.js 官方展示](https://mozilla.github.io/pdf.js/web/viewer.html). 本页 PDF 素材来源。')]),
entry('30','富文本折叠详情',['全组'],'适合附录、长表格和补充说明；可包含多种富文本。',[layout('details','### 补充材料\n\n**可在这里放入方法补充和来源。**\n\n| 文件 | 状态 |\n| --- | --- |\n| 图像 | 示例 |\n| 记录 | 示例 |\n\n- 第一项\n- 第二项',{label:'展开阅读完整附录'})]),
entry('31','成员卡片',['HP','设计'],'头像、角色和简介；以下为虚构角色。',[layout('people',`### 示例成员 A {role="Wet Lab · 虚构角色" img="${img}before.svg"}\n\n负责示例材料整理。\n\n### 示例成员 B {role="Dry Lab · 虚构角色" img="${img}after.svg"}\n\n负责示例图表整理。\n\n### 示例成员 C {role="HP · 虚构角色"}\n\n无头像时显示姓名缩写。`)]),
entry('32','导语与图形容器',['全组'],'导语强调开篇摘要；图形容器支持独立图注和来源。',[layout('lead','把一页最重要的问题与目标放在这里。导语用于引导阅读，详细证据放到后续章节。'),layout('figure','**Fig. 3** 人工绘制的视觉示例。',{attributes:`src="${img}after.svg" alt="几何示意图" credit="来源：本地演示素材"`})]),
];
