/* NKU homepage — 02 world map + 03 China maps */
(function () {
  'use strict';
  var H = window.NKUH; if (!H) return;
  var GEO = window.NKU_GEO || {}, LAND = window.NKU_LAND || {};
  var RAMP = [[243, 220, 194], [244, 162, 97], [239, 111, 108], [192, 78, 168], [110, 79, 210]];
  function ramp(v, a) {
    v = H.clamp(v, 0, 1) * (RAMP.length - 1); var i = Math.min(RAMP.length - 2, Math.floor(v)), f = v - i, A = RAMP[i], B = RAMP[i + 1];
    return 'rgba(' + Math.round(H.lerp(A[0], B[0], f)) + ',' + Math.round(H.lerp(A[1], B[1], f)) + ',' + Math.round(H.lerp(A[2], B[2], f)) + ',' + (a == null ? 1 : a) + ')';
  }
  /* Plant-feeding nematode abundance: van den Hoogen et al. 2020, Scientific Data 7:103 (CC0).
     js/home-abundance.js is generated by tools/build_abundance.py from the published csv.
     One dot per sampled 1-km pixel; nothing is interpolated. World and China share one scale. */
  var PTS = (window.NKU_ABUNDANCE || []).filter(function (p) { return isFinite(p.lon) && isFinite(p.lat) && p.value >= 0; });
  var META = window.NKU_ABUNDANCE_META || {};
  var REAL = PTS.length > 100, LMAX = 0;
  PTS.forEach(function (p) { p.l = Math.log10(p.value + 1); LMAX = Math.max(LMAX, p.l); });
  function lv(p) { return LMAX ? p.l / LMAX : 0; }
  function median(a) { if (!a.length) return 0; var b = a.slice().sort(function (x, y) { return x - y; }), m = b.length >> 1; return b.length % 2 ? b[m] : (b[m - 1] + b[m]) / 2; }
  function fmt(v) { return v >= 100 ? Math.round(v).toLocaleString('en-US') : v.toFixed(1); }
  var ABUND_SRC = 'van den Hoogen et al. 2020, <i>Scientific Data</i> 7: 103 (data CC0)';
  function continent(lon, lat) {
    if (lon < -30) return lat > 12 ? 'na' : 'sa';
    if (lon > 110 && lat < -10 || lon > 160) return 'oc';
    if (lon < 60 && lat > 35 && !(lon > 26 && lat < 42)) return 'eu';
    if (lon < 52 && lat <= 35 && !(lon > 34 && lat > 12)) return 'af';
    return 'as';
  }
  var CONT = { na: 'North America', sa: 'South America', eu: 'Europe', af: 'Africa', as: 'Asia', oc: 'Oceania' };
  /* documented crop losses: every figure comes from the source named with it */
  var CASES = [
    { lon: -91, lat: 41, k: 'na', region: 'United States', nem: 'Soybean cyst nematode (<i>Heterodera glycines</i>)', crop: 'Soybean',
      loss: 'More than US$1 billion of soybean yield lost a year in the USA (2006–2009 estimate)',
      src: 'Koenning &amp; Wrather 2010, <i>Plant Health Progress</i> 11: 5; cited in Peng et al. 2021' },
    { lon: -55.2, lat: -12.1, k: 'sa', region: 'Brazil, Mato Grosso', nem: 'Root-lesion nematode (<i>Pratylenchus brachyurus</i>)', crop: 'Soybean',
      loss: 'Average loss of 21% of potential yield across a mapped commercial field, 2011/12 season',
      src: 'Franchini et al., Embrapa Soja, <i>Agricultura de precisão: resultados de um novo olhar</i> (2014)' },
    { lon: 5, lat: 52.5, k: 'eu', region: 'Europe', nem: 'Potato cyst nematodes (<i>Globodera pallida</i>, <i>G. rostochiensis</i>)', crop: 'Potato',
      loss: 'Together about 9% of potato production lost worldwide; regulated as quarantine pests in the EU',
      src: 'Kantor et al. 2022, <i>Horticulturae</i> 8: 208; Commission Implementing Regulation (EU) 2019/2072' },
    { lon: 32.6, lat: 0.4, k: 'af', region: 'Uganda', nem: 'Burrowing and spiral nematodes (<i>Radopholus similis</i>, <i>Helicotylenchus multicinctus</i>)', crop: 'East African highland banana',
      loss: 'Production 30–38% lower in infested plots than in clean plots',
      src: 'Speijer, Kajumba &amp; Ssango 1999, <i>Int. J. Pest Management</i> 45: 41–49' },
    { lon: 126.6, lat: 45.8, k: 'as', region: 'China', nem: 'Soybean cyst nematode (<i>Heterodera glycines</i>)', crop: 'Soybean',
      loss: 'More than US$120 million of soybean yield lost a year', china: true,
      src: 'Peng et al. 2021, <i>Phytopathology Research</i> 3: 19' },
    { lon: 150, lat: -28, k: 'oc', region: 'Australia', nem: 'Root-lesion nematodes (<i>Pratylenchus thornei</i>, <i>P. neglectus</i>)', crop: 'Wheat',
      loss: 'About AU$123 million of wheat lost a year nationally (10 years to 2008)',
      src: 'Murray &amp; Brennan 2010, GRDC; cited in Thompson et al., GRDC Update 2012' }
  ];

  /* ================= WORLD ================= */
  function world() {
    var sec = H.$('[data-world]'); if (!sec || !LAND.d) return;
    var pin = H.$('.world__pin', sec), mask = H.$('[data-world-mask]', sec), title = H.$('[data-world-title]', sec);
    var svg = H.$('[data-world-svg]', sec), cv = H.$('[data-world-heat]', sec), marks = H.$('[data-world-marks]', sec);
    var card = H.$('[data-flipcard]', sec); pin.appendChild(card);
    var NS = 'http://www.w3.org/2000/svg';
    var land = document.createElementNS(NS, 'path'); land.setAttribute('d', LAND.d); land.setAttribute('fill', '#e8d6be'); svg.appendChild(land);
    var cn = document.createElementNS(NS, 'path');
    cn.setAttribute('d', (GEO.china && GEO.china.outline || []).map(function (r) { return 'M' + r.map(function (p) { return ((p[0] + 180) * 2.5).toFixed(1) + ',' + ((84 - p[1]) * 2.5).toFixed(1); }).join('L') + 'Z'; }).join(''));
    cn.setAttribute('fill', 'none'); cn.setAttribute('stroke', '#7e0c6e'); cn.setAttribute('stroke-width', '1.3'); cn.setAttribute('stroke-dasharray', '3 3'); cn.setAttribute('opacity', '.8');
    cn.style.pointerEvents = 'none'; svg.appendChild(cn);
    var landPath = new Path2D(LAND.d);
    var ctx, w, h, hover = null, bloom = 0;
    var rng = H.rand(5);
    PTS.forEach(function (p) { p.r = rng(); p.k = continent(p.lon, p.lat); });
    if (!REAL) sec.classList.add('world--nodata');
    else { var nEl = H.$('[data-abundance-n]', sec); if (nEl) nEl.textContent = PTS.length.toLocaleString('en-US'); }
    function size() { var r = cv.getBoundingClientRect(); w = r.width; h = r.height; ctx = H.fit(cv, w, h, 2); draw(); }
    function X(lon) { return (lon + 180) * 2.5 / 900 * w; }
    function Y(lat) { return (84 - lat) * 2.5 / 350 * h; }
    if (!REAL) sec.classList.add('world--nodata');
    function draw() {
      if (!ctx) return;
      ctx.clearRect(0, 0, w, h);
      if (!REAL) return;
      var k = w / 900;
      PTS.forEach(function (p) {
        if (p.r > bloom * 1.15) return;
        var a = hover ? (p.k === hover ? .95 : .22) : .85, v = lv(p);
        ctx.fillStyle = ramp(v, a); ctx.beginPath(); ctx.arc(X(p.lon), Y(p.lat), (1.4 + v * 1.8) * k * 1.5, 0, 6.29); ctx.fill();
      });
    }
    // markers
    CASES.forEach(function (c, i) {
      var b = document.createElement('button'); b.type = 'button'; b.className = 'wmark';
      b.style.left = ((c.lon + 180) * 2.5 / 9) + '%'; b.style.top = ((84 - c.lat) * 2.5 / 3.5) + '%'; b.style.setProperty('--d', (i * .35) + 's');
      b.setAttribute('aria-label', c.region + ': documented crop loss');
      b.addEventListener('click', function (e) { e.stopPropagation(); openCase(c, e); });
      b.addEventListener('pointerenter', function () { hover = c.k; draw(); });
      b.addEventListener('pointerleave', function () { hover = null; draw(); });
      marks.appendChild(b);
    });
    function lonlat(e) { var r = svg.getBoundingClientRect(); return [(e.clientX - r.left) / r.width * 360 - 180, 84 - (e.clientY - r.top) / r.height * 140]; }
    svg.addEventListener('pointermove', function (e) {
      var ll = lonlat(e), k = continent(ll[0], ll[1]);
      if (k !== hover) { hover = k; draw(); }
    });
    svg.addEventListener('pointerleave', function () { hover = null; draw(); });
    svg.addEventListener('click', function (e) {
      var ll = lonlat(e);
      if (ll[0] > 73 && ll[0] < 135 && ll[1] > 18 && ll[1] < 54 && inChina(ll[0], ll[1])) { goChina(); return; }
      open(continent(ll[0], ll[1]), e);
    });
    function inChina(lon, lat) {
      var g = GEO.china; if (!g) return false;
      var r = Math.floor((g.north - lat) / g.step), c = Math.floor((lon - g.west) / g.step), row = g.rows_mask[r];
      if (!row) return false;
      return row.split(',').some(function (run) { var a = run.split(':'); return c >= +a[0] && c < +a[0] + +a[1]; });
    }
    function place(e) {
      var pr = pin.getBoundingClientRect(), x = e.clientX - pr.left, y = e.clientY - pr.top, cw = 300;
      var left = x + 16 + cw > pr.width - 12 ? x - cw - 16 : x + 16, top = H.clamp(y - 40, 70, pr.height - 300);
      card.style.left = left + 'px'; card.style.top = top + 'px';
      card.style.setProperty('--ox', (left < x ? '100%' : '0'));
      card.hidden = false; card.classList.remove('is-open'); void card.offsetWidth; card.classList.add('is-open');
    }
    function fill(kicker, title, rows, foot) {
      H.$('[data-flip-kicker]', card).textContent = kicker;
      H.$('[data-flip-title]', card).textContent = title;
      H.$('[data-flip-body]', card).innerHTML = '<dl>' + rows.map(function (r) { return '<dt>' + r[0] + '</dt><dd>' + r[1] + '</dd>'; }).join('') + '</dl>' + (foot ? '<small>' + foot + '</small>' : '');
    }
    /* a continent: abundance measured in its sampled pixels */
    function open(k, e) {
      var vals = PTS.filter(function (p) { return p.k === k; }).map(function (p) { return p.value; });
      var cs = CASES.filter(function (c) { return c.k === k; })[0];
      if (!REAL || !vals.length) { if (cs) openCase(cs, e); return; }
      fill('Plant-feeding nematode abundance', CONT[k], [
        ['Median', fmt(median(vals)) + ' individuals per 100 g dry soil'],
        ['Sampled', vals.length.toLocaleString('en-US') + ' pixels of about 1 km'],
        ['Data', 'Direct soil samples, averaged per pixel'],
        ['Source', ABUND_SRC]
      ], 'Abundance indicates potential exposure, not crop loss or disease severity.' + (cs ? ' <button type="button" class="flipcard__more" data-case>Documented loss in ' + cs.region + '</button>' : ''));
      var more = H.$('[data-case]', card); if (more) more.addEventListener('click', function (ev) { ev.stopPropagation(); openCase(cs, ev); });
      place(e); hover = k; draw();
    }
    /* a documented loss, with its source */
    function openCase(c, e) {
      fill('Documented crop loss', c.region, [['Nematode', c.nem], ['Crop', c.crop], ['Loss', c.loss], ['Source', c.src]],
        c.china ? '<button type="button" class="flipcard__more" data-go-china>See the China maps</button>' : '');
      var g = H.$('[data-go-china]', card); if (g) g.addEventListener('click', function (ev) { ev.stopPropagation(); goChina(); });
      place(e); hover = c.k; draw();
    }
    function closeCard() { card.classList.remove('is-open'); setTimeout(function () { if (!card.classList.contains('is-open')) card.hidden = true; }, 400); }
    H.$('[data-flip-close]', card).addEventListener('click', closeCard);
    document.addEventListener('keydown', function (e) { if (e.key === 'Escape') closeCard(); });
    document.addEventListener('pointerdown', function (e) { if (!card.hidden && !card.contains(e.target) && !svg.contains(e.target) && !marks.contains(e.target)) closeCard(); });
    function goChina() {
      closeCard(); var t = H.$('#china'); if (!t) return;
      scrollTo({ top: t.getBoundingClientRect().top + scrollY, behavior: H.reduced ? 'auto' : 'smooth' });
      setTimeout(function () { var m = H.$('[data-cmap="env"]'); if (m) m.classList.add('is-ping'); }, 900);
    }
    H.$('[data-world-china]', sec).addEventListener('click', goChina);

    /* iris: the flashlight's last spot on the previous page grows until it uncovers the map */
    var t0 = performance.now(), opened = false, counted = false, iris = null;
    function setMask(x, y, r) { mask.style.setProperty('--mx', x + 'px'); mask.style.setProperty('--my', y + 'px'); mask.style.setProperty('--mr', r + 'px'); }
    function openNow() { iris = null; opened = true; sec.classList.add('is-open'); bloom = 1; draw(); if (!counted) { counted = true; count(); } }
    function closeNow() { opened = false; counted = false; sec.classList.remove('is-open'); bloom = 0; draw(); setMask(-999, -999, 0); }
    function tick(now) {
      if (iris) {
        var pr = pin.getBoundingClientRect(), k = H.clamp((now - iris.t0) / iris.dur, 0, 1), hold = .12;
        var e = H.ease(H.clamp((k - hold) / (1 - hold), 0, 1)), far = Math.hypot(Math.max(iris.x, pr.width - iris.x), Math.max(iris.y, pr.height - iris.y)) + 80;
        var wob = (1 - e) * 5, x = iris.x + Math.sin(now / 90) * wob, y = iris.y + Math.cos(now / 110) * wob;
        setMask(x, y, H.lerp(iris.r, far, e));
        bloom = H.smooth(.35, .95, k); draw();
        if (!counted && k > .45) { counted = true; count(); }
        if (k >= 1) openNow();
      }
      if (visible) requestAnimationFrame(tick);
    }
    /* native scrolling: the section pins and the iris follows scroll, from the flashlight's last spot */
    function scrollIris() { return !(H.pager && H.pager.isPaged()) && innerWidth > 980 && !H.reduced; }
    function onIrisScroll() {
      if (!sec.classList.contains('is-iris')) return;
      var p = H.progress(sec), k = H.smooth(.02, .5, p), pr = pin.getBoundingClientRect();
      var L = H.lastLight || { x: pr.width * .5, y: pr.height * .55, r: 140 };
      var far = Math.hypot(Math.max(L.x, pr.width - L.x), Math.max(L.y, pr.height - L.y)) + 80;
      if (k >= 1) { if (!opened) openNow(); return; }
      if (opened) { opened = false; sec.classList.remove('is-open'); }
      setMask(L.x, L.y, p <= 0 ? 0 : H.lerp(Math.max(40, L.r * .85), far, H.ease(k)));
      bloom = H.smooth(.2, .5, p); draw();
      if (!counted && k > .4) { counted = true; count(); }
    }
    addEventListener('scroll', onIrisScroll, { passive: true });
    H.scene('world', {
      cutIn: true,
      set: function (i, dir) {
        if (scrollIris()) { sec.classList.add('is-iris'); onIrisScroll(); return; }
        sec.classList.remove('is-iris');
        if (dir < 0) openNow(); else closeNow();
      },
      enter: function (dir, info) {
        if (opened) return 0;
        if (!info || !info.cut || !H.lastLight || innerWidth <= 980) { openNow(); return 0; }
        var L = H.lastLight; iris = { x: L.x, y: L.y, r: Math.max(40, L.r * .85), t0: performance.now(), dur: 1500 };
        setMask(iris.x, iris.y, iris.r); requestAnimationFrame(tick); return 1500;
      },
      ff: function () { openNow(); }
    });
    function count() {
      var el = H.$('[data-usd]', sec); if (!el || H.reduced) return;
      var s = performance.now();
      (function step(n) { var k = H.ease(H.clamp((n - s) / 1400, 0, 1)); el.textContent = 'US$' + Math.round(173 * k); if (k < 1) requestAnimationFrame(step); })(s);
    }
    var visible = false;
    H.onView(sec, function (v) { var was = visible; visible = v; if (v && !was) requestAnimationFrame(tick); if (v && !opened && !(H.pager && H.pager.isPaged()) && !sec.classList.contains('is-iris')) openNow(); });
    size(); addEventListener('resize', size);
  }

  /* ================= CHINA ================= */
  var PROV = { Heilongjiang: [126.6, 45.8], Jilin: [125.3, 43.9], Liaoning: [123.4, 41.8], 'Inner Mongolia': [111.7, 40.8], Beijing: [116.4, 39.9], Hebei: [114.5, 38], Shanxi: [112.5, 37.9], Shandong: [117, 36.7], Henan: [113.7, 34.8], Anhui: [117.3, 31.9], Jiangsu: [118.8, 32.1], Shanghai: [121.5, 31.2], Zhejiang: [120.2, 30.3], Jiangxi: [115.9, 28.7], Hubei: [114.3, 30.6], Shaanxi: [108.9, 34.3], Gansu: [103.8, 36.1], Ningxia: [106.3, 38.5], Xinjiang: [87.6, 43.8], Guizhou: [106.7, 26.6], Yunnan: [102.7, 25], Guangxi: [108.3, 22.8], Fujian: [119.3, 26.1], Guangdong: [113.3, 23.1], Hainan: [110.3, 20], Hunan: [113, 28.2], Qinghai: [101.8, 36.6], Sichuan: [104.1, 30.7] };
  var SCN = ['Heilongjiang', 'Jilin', 'Liaoning', 'Inner Mongolia', 'Beijing', 'Hebei', 'Henan', 'Shandong', 'Shanxi', 'Anhui', 'Jiangsu', 'Shanghai', 'Zhejiang', 'Jiangxi', 'Hubei', 'Shaanxi', 'Gansu', 'Ningxia', 'Xinjiang', 'Guizhou', 'Yunnan', 'Guangxi'];
  var RKN = ['Anhui', 'Fujian', 'Guangdong', 'Guangxi', 'Guizhou', 'Hainan', 'Hebei', 'Heilongjiang', 'Henan', 'Hubei', 'Hunan', 'Jiangsu', 'Jiangxi', 'Inner Mongolia', 'Qinghai', 'Shaanxi', 'Shandong', 'Sichuan', 'Yunnan', 'Zhejiang', 'Xinjiang'];
  var TEXT = {
    env: { k: 'Environment', t: 'Plant-feeding nematode abundance in China',
      b: '<p>Each dot is a sampled 1-km pixel from the global soil nematode database. Unit and color scale are the same as on the world map; China is not re-scaled.</p><p>Abundance indicates potential exposure. It is not crop loss or disease severity.</p><small>Source: ' + ABUND_SRC + '.</small>' },
    scn: { k: 'Soybean cyst nematode', t: 'Distribution and impact of soybean cyst nematode in China',
      b: '<ul><li><b>Where</b><span>Reported in 22 provinces. Northeast China and the Huanghuaihai Valley, the two main soybean regions, are outlined.</span></li><li><b>Loss</b><span>Yield usually falls by about 20–30% in infested fields and by 60–70% in badly infested ones, sometimes to nothing. Estimated losses exceed US$120 million a year.</span></li><li><b>Hosts</b><span>Soybean and other legumes such as mung bean, pea and common bean. Also recorded on Rehmannia, Paulownia, sesame, tobacco and tomato.</span></li></ul><small>Markers show reported presence by province, not how severe damage is. There is no comparable loss figure per province, so the national estimate is not split among them. Source: Peng et al. 2021, <i>Phytopathology Research</i> 3: 19.</small>' },
    rkn: { k: 'Southern root-knot nematode', t: 'Reported distribution and major hosts of southern root-knot nematode in China',
      b: '<ul><li><b>Where</b><span>Provincial records in 20 provinces (CABI), plus Xinjiang, where a 2021–23 survey found root-knot nematodes in 57 of 130 vegetable samples, mostly <i>M. incognita</i>.</span></li><li><b>Hosts</b><span>More than 3,000 plant species, from tomato, pepper, eggplant, cucumber and melons to legumes, tobacco, cotton, peanut, sweet potato, banana, sugarcane and medicinal plants.</span></li><li><b>Hunan</b><span>In vegetable areas, disease incidence reached 80% in greenhouses and about 10% in open fields; <i>M. incognita</i> made up 87% of identified populations. These are incidence and species shares, not yield losses.</span></li></ul><small>A record means the species has been reported, not that the whole province is badly affected. There is no recent, reliable national loss figure for this species. Sources: CABI distribution map of <i>M. incognita</i>; Zhou et al. 2024, <i>J. Integr. Agric.</i>; Cheng, Zhang &amp; He 2010 (Hunan survey); host range: <i>New Phytologist</i>, doi:10.1111/nph.71431.</small>' }
  };

  function china() {
    var sec = H.$('[data-china]'); if (!sec || !GEO.china) return;
    var G = GEO.china, maps = {};
    // the abundance map needs the measured database file; the two species maps come from the literature
    if (!REAL) { sec.classList.add('cn--two'); H.$$('[data-cmap="env"]', sec).forEach(function (f) { f.remove(); }); }
    H.$$('[data-cmap]', sec).forEach(function (fig) {
      var kind = fig.getAttribute('data-cmap'), m = makeMap(kind, H.$('canvas', fig), false);
      maps[kind] = m;
      H.$('[data-cmap-open]', fig).addEventListener('click', function () { openFocus(kind); });
      H.once(fig, function () { m.intro(); }, .3);
      H.$$('[data-sp]', fig).forEach(function (b) {
        b.addEventListener('click', function () { b.setAttribute('aria-pressed', b.getAttribute('aria-pressed') === 'true' ? 'false' : 'true'); m.filter[b.getAttribute('data-sp')] = b.getAttribute('aria-pressed') === 'true'; m.kick(); });
      });
    });
    addEventListener('resize', function () { Object.keys(maps).forEach(function (k) { maps[k].resize(); }); });
    // focus dialog
    var dlg = H.$('[data-cfocus]', sec), fcv = H.$('[data-cfocus-canvas]', sec), order = REAL ? ['env', 'scn', 'rkn'] : ['scn', 'rkn'], cur = 0, fm = null, lastFocus;
    function openFocus(kind) {
      lastFocus = document.activeElement; cur = order.indexOf(kind);
      dlg.hidden = false; requestAnimationFrame(function () { dlg.classList.add('is-open'); fill(); });
      document.documentElement.style.overflow = 'hidden';
      H.$('[data-cfocus-close]', dlg).focus();
    }
    function fill() {
      var kind = order[cur], T = TEXT[kind];
      dlg.style.setProperty('--c', H.$('[data-cmap="' + kind + '"]', sec).style.getPropertyValue('--c'));
      H.$('[data-cf-kicker]', dlg).textContent = T.k; H.$('[data-cf-title]', dlg).textContent = T.t; H.$('[data-cf-body]', dlg).innerHTML = T.b;
      if (fm) fm.destroy(); fm = makeMap(kind, fcv, true); fm.intro();
    }
    function close() { dlg.classList.remove('is-open'); document.documentElement.style.overflow = ''; setTimeout(function () { dlg.hidden = true; if (fm) { fm.destroy(); fm = null; } }, 350); if (lastFocus) lastFocus.focus(); }
    H.$('[data-cfocus-close]', dlg).addEventListener('click', close);
    dlg.addEventListener('click', function (e) { if (e.target === dlg) close(); });
    H.$('[data-cf-prev]', dlg).addEventListener('click', function () { cur = (cur + order.length - 1) % order.length; fill(); });
    H.$('[data-cf-next]', dlg).addEventListener('click', function () { cur = (cur + 1) % order.length; fill(); });
    document.addEventListener('keydown', function (e) { if (!dlg.hidden && e.key === 'Escape') close(); });

    function inside(lon, lat) {
      var r = Math.floor((G.north - lat) / G.step), c = Math.floor((lon - G.west) / G.step), row = G.rows_mask[r];
      if (!row) return false;
      return row.split(',').some(function (run) { var a = run.split(':'); return c >= +a[0] && c < +a[0] + +a[1]; });
    }

    function makeMap(kind, cv, big) {
      var ctx, w, h, s, ox, oy, mouse = null, t0 = performance.now(), introT = -1, raf = 0, alive = true, yaw = 0, tilt = 0;
      var only = kind === 'scn' || kind === 'rkn' ? kind : null;
      if (only) kind = 'agr';
      var m = { filter: { scn: !only || only === 'scn', rkn: !only || only === 'rkn' } };
      var rng = H.rand(9);
      // projection: main map lon 73..135.5, lat 17..54 (+ South China Sea inset)
      function size() {
        var r = cv.getBoundingClientRect(); w = r.width; h = r.height || r.width * .86; ctx = H.fit(cv, w, h, 2);
        s = Math.min(w / (62.5 * .84), h / 38.5) * .94; ox = (w - 62.5 * .84 * s) / 2; oy = (h - 38.5 * s) / 2 + 2;
      }
      function P(lon, lat) { return [ox + (lon - 73) * .84 * s, oy + (54 - lat) * s]; }
      var inset = { lon0: 106, lon1: 124, lat0: 3, lat1: 24 };
      function PI(lon, lat) { var bw = w * .17, bh = bw * 1.25, bx = w - bw - 6, by = h - bh - 6; return [bx + (lon - inset.lon0) / (inset.lon1 - inset.lon0) * bw, by + (inset.lat1 - lat) / (inset.lat1 - inset.lat0) * bh]; }
      function outline(c, proj, style) {
        G.outline.forEach(function (ring) {
          c.beginPath(); ring.forEach(function (p, i) { var q = proj(p[0], p[1]); i ? c.lineTo(q[0], q[1]) : c.moveTo(q[0], q[1]); }); c.closePath(); style(c);
        });
      }
      function insetBox(c) {
        var bw = w * .17, bh = bw * 1.25, bx = w - bw - 6, by = h - bh - 6;
        c.save(); c.strokeStyle = 'rgba(255,255,255,.35)'; c.lineWidth = 1; c.strokeRect(bx, by, bw, bh);
        c.beginPath(); c.rect(bx, by, bw, bh); c.clip();
        outline(c, PI, function (c) { c.fillStyle = 'rgba(255,255,255,.3)'; c.fill(); c.strokeStyle = 'rgba(255,255,255,.7)'; c.lineWidth = .8; c.stroke(); });
        c.strokeStyle = 'rgba(255,255,255,.55)'; c.lineWidth = 1;
        (G.maritime || []).forEach(function (l) { c.beginPath(); l.forEach(function (p, i) { var q = PI(p[0], p[1]); i ? c.lineTo(q[0], q[1]) : c.moveTo(q[0], q[1]); }); c.stroke(); });
        c.restore();
      }
      function clipMain(c) { c.beginPath(); c.rect(0, 0, w, P(0, 17.5)[1]); c.clip(); }

      /* ---- env: hex dot matrix ---- */
      var hexes = [];
      if (kind === 'env') {
        PTS.forEach(function (p) { if (inside(p.lon, p.lat)) hexes.push({ lon: p.lon, lat: p.lat, v: lv(p), p: p, d: (p.lon - 73) / 62 + rng() * .25 }); });
      }
      /* ---- agr markers ---- */
      var marks = [];
      if (kind === 'agr') {
        SCN.forEach(function (n, i) { marks.push({ n: n, sp: 'scn', ll: PROV[n], d: i * .04, off: !only && RKN.indexOf(n) >= 0 ? -1 : 0 }); });
        RKN.forEach(function (n, i) { marks.push({ n: n, sp: 'rkn', ll: PROV[n], d: .3 + i * .04, off: !only && SCN.indexOf(n) >= 0 ? 1 : 0, note: n === 'Xinjiang' ? 'found in vegetable fields, 2021–23 survey' : '' }); });
      }
      var mesh = [], bars = [];
      function P3(lon, lat, z) {
        var q = P(lon, lat), cx = w / 2, cy = h / 2, dx = q[0] - cx, dy = q[1] - cy;
        var ca = Math.cos(yaw), sa = Math.sin(yaw), rx = dx * ca - dy * sa, ry = dx * sa + dy * ca;
        var ct = .62 + tilt * .08;
        return [cx + rx * .96, cy + 18 + ry * ct - (z || 0)];
      }

      function draw() {
        raf = 0; if (!alive) return;
        var t = (performance.now() - t0) / 1000, it = introT < 0 ? 0 : H.clamp((performance.now() - introT) / 1600, 0, 1);
        ctx.clearRect(0, 0, w, h);
        if (kind === 'env') {
          ctx.save(); clipMain(ctx);
          outline(ctx, P, function (c) { c.fillStyle = 'rgba(255,255,255,.04)'; c.fill(); c.strokeStyle = 'rgba(255,255,255,.55)'; c.lineWidth = 1.1; c.stroke(); });
          hexes.forEach(function (d) {
            var q = P(d.lon, d.lat), k = H.clamp((it * 1.5 - d.d) * 3, 0, 1); if (k <= 0) return;
            var near = 0; if (mouse) { var dd = Math.hypot(q[0] - mouse[0], q[1] - mouse[1]); near = Math.max(0, 1 - dd / (big ? 90 : 60)); }
            var r = (big ? 2.6 : 2.3) * s / 8 * (1 + near * 1.2) * k;
            ctx.fillStyle = ramp(d.v, .82 + near * .18);
            if (near > .5) { ctx.shadowColor = ramp(d.v, 1); ctx.shadowBlur = 8; } else ctx.shadowBlur = 0;
            ctx.beginPath(); ctx.arc(q[0], q[1], r, 0, 6.29); ctx.fill();
          });
          ctx.restore(); ctx.shadowBlur = 0; insetBox(ctx);
        }
        if (kind === 'agr') {
          ctx.save(); clipMain(ctx);
          outline(ctx, P, function (c) { c.fillStyle = 'rgba(255,255,255,.035)'; c.fill(); c.strokeStyle = 'rgba(255,255,255,.85)'; c.lineWidth = 1.4; c.shadowColor = 'rgba(255,255,255,.5)'; c.shadowBlur = 6; c.stroke(); c.shadowBlur = 0; });
          // key soybean regions
          (m.filter.rkn && !m.filter.scn ? [] : [[126, 45, 5.5, 3.6], [116, 35.5, 4.2, 3.2]]).forEach(function (e, i) {
            var q = P(e[0], e[1]); ctx.save(); ctx.setLineDash([4, 5]); ctx.lineDashOffset = -t * 8; ctx.strokeStyle = 'rgba(255,211,77,' + (.35 + .5 * it) + ')'; ctx.lineWidth = 1.3;
            ctx.beginPath(); ctx.ellipse(q[0], q[1], e[2] * s * .84, e[3] * s, -.3, 0, 6.29); ctx.stroke(); ctx.restore();
          });
          // hatch texture (collage feel)
          ctx.save(); var cp = new Path2D(); G.outline.forEach(function (ring) { ring.forEach(function (p, i) { var q = P(p[0], p[1]); i ? cp.lineTo(q[0], q[1]) : cp.moveTo(q[0], q[1]); }); cp.closePath(); });
          ctx.clip(cp); ctx.globalAlpha = .1; ctx.strokeStyle = '#fff'; ctx.lineWidth = 1;
          for (var hx = -h; hx < w; hx += 8) { ctx.beginPath(); ctx.moveTo(hx, P(0, 45)[1]); ctx.lineTo(hx + 50, P(0, 37)[1]); ctx.stroke(); }
          ctx.globalAlpha = .08; for (var hy = P(0, 30)[1]; hy < P(0, 22)[1]; hy += 6) { ctx.beginPath(); ctx.moveTo(0, hy); ctx.lineTo(w, hy); ctx.stroke(); }
          ctx.restore();
          var hot = null;
          marks.forEach(function (mk) {
            if (!m.filter[mk.sp]) return;
            var k = H.ease(H.clamp((it * 1.6 - mk.d) * 2.5, 0, 1)); if (k <= 0) return;
            var q = P(mk.ll[0], mk.ll[1]); q[0] += mk.off * s * .55;
            var near = mouse && Math.hypot(q[0] - mouse[0], q[1] - mouse[1]) < 12; if (near) hot = mk;
            var sz = (big ? 8 : 5.6) * k * (near ? 1.6 : 1) * (1 + Math.sin(t * 2 + mk.d * 10) * .06);
            ctx.save(); ctx.translate(q[0], q[1]);
            if (mk.sp === 'scn') { ctx.fillStyle = '#ffa24a'; ctx.shadowColor = '#ffa24a'; ctx.shadowBlur = 10; ctx.beginPath(); ctx.moveTo(0, -sz); ctx.lineTo(sz * .9, sz * .7); ctx.lineTo(-sz * .9, sz * .7); ctx.closePath(); ctx.fill(); }
            else { ctx.fillStyle = '#53d8f2'; ctx.shadowColor = '#53d8f2'; ctx.shadowBlur = 10; ctx.beginPath(); ctx.arc(0, 0, sz * .75, 0, 6.29); ctx.fill(); ctx.fillStyle = '#0f2a33'; ctx.beginPath(); ctx.arc(0, 0, sz * .28, 0, 6.29); ctx.fill(); }
            ctx.restore();
          });
          ctx.restore(); insetBox(ctx);
          m.hot = hot;
        }
        if (it < 1 || mouse || kind === 'agr') m.kick();
      }
      m.kick = function () { if (!raf && alive && m.visible !== false) raf = requestAnimationFrame(draw); };
      m.intro = function () { introT = performance.now(); m.kick(); };
      m.resize = function () { size(); m.kick(); };
      m.destroy = function () { alive = false; cv.removeEventListener('pointermove', move); cv.removeEventListener('pointerleave', leave); cv.removeEventListener('pointerdown', move); };
      function move(e) {
        var r = cv.getBoundingClientRect(); mouse = [e.clientX - r.left, e.clientY - r.top]; m.kick();
        setTimeout(function () {
          var html = '';
          if (kind === 'env' && mouse) {
            var best = null, bd = 14;
            hexes.forEach(function (d) { var q = P(d.lon, d.lat), dd = Math.hypot(q[0] - mouse[0], q[1] - mouse[1]); if (dd < bd) { bd = dd; best = d; } });
            if (best) html = '<b>' + best.lon.toFixed(2) + '°E, ' + best.lat.toFixed(2) + '°N</b>' + fmt(best.p.value) + ' plant-feeding nematodes per 100 g dry soil' + (best.p.n > 1 ? ' (mean of ' + best.p.n + ' samples)' : '');
          }
          if (kind === 'agr' && m.hot) html = '<b>' + m.hot.n + '</b>' + (m.hot.sp === 'scn' ? 'Soybean cyst nematode reported (Peng et al. 2021)' : 'Southern root-knot nematode ' + (m.hot.note || 'recorded (CABI)'));
          H.tip(html, e.clientX, e.clientY);
        }, 20);
      }
      function leave() { mouse = null; H.tip(null); m.kick(); }
      cv.addEventListener('pointermove', move); cv.addEventListener('pointerdown', move); cv.addEventListener('pointerleave', leave);
      H.onView(cv, function (v) { m.visible = v; if (v) m.kick(); });
      size();
      return m;
    }
  }
  H.ready(function () { world(); china(); });
})();
