#!/usr/bin/env python3
"""Build the homepage abundance layer from van den Hoogen et al. (2020).

The downloaded file is already aggregated to 30 arc-second pixels. This
script copies only Pixel_Long, Pixel_Lat and Herbivores; it does not average,
interpolate or round the source values. Rows with missing or invalid values
are skipped and counted in the generated metadata.
"""

import argparse
import csv
import datetime as dt
import hashlib
import json
import math
import pathlib
import sys
import urllib.error
import urllib.request
from decimal import Decimal, InvalidOperation


ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "js" / "home-abundance.js"
SOURCE_URL = (
    "https://raw.githubusercontent.com/hooge104/2020_global_nematode_dataset/"
    "master/data/nematode_aggregated_wCovariateData.csv"
)
CITATION = (
    "van den Hoogen, J. et al. (2020) A global database of soil nematode "
    "abundance and functional group composition. Scientific Data 7:103. "
    "doi:10.1038/s41597-020-0437-3"
)
LICENSE = "CC0 1.0 Universal"
LICENSE_URL = "https://creativecommons.org/publicdomain/zero/1.0/"


def read_source(path):
    if path:
        return pathlib.Path(path).read_bytes(), str(pathlib.Path(path))
    request = urllib.request.Request(
        SOURCE_URL, headers={"User-Agent": "NKU-iGEM-wiki-build"}
    )
    with urllib.request.urlopen(request, timeout=60) as response:
        return response.read(), SOURCE_URL


def decimal_value(value):
    try:
        number = Decimal(str(value).strip())
    except (InvalidOperation, ValueError):
        return None
    if not number.is_finite():
        return None
    return number


def build_points(text):
    rows = list(csv.DictReader(text.splitlines()))
    required = {"Pixel_Lat", "Pixel_Long", "Herbivores"}
    missing = required.difference(rows[0].keys() if rows else set())
    if missing:
        raise ValueError("missing required columns: " + ", ".join(sorted(missing)))

    skipped = {"missing_or_invalid": 0, "out_of_bounds": 0, "negative": 0}
    points = []
    for row in rows:
        lat_raw = row.get("Pixel_Lat", "").strip()
        lon_raw = row.get("Pixel_Long", "").strip()
        value_raw = row.get("Herbivores", "").strip()
        lat = decimal_value(lat_raw)
        lon = decimal_value(lon_raw)
        value = decimal_value(value_raw)
        if lat is None or lon is None or value is None:
            skipped["missing_or_invalid"] += 1
            continue
        if not (-90 <= float(lat) <= 90 and -180 <= float(lon) <= 180):
            skipped["out_of_bounds"] += 1
            continue
        if value < 0:
            skipped["negative"] += 1
            continue
        points.append({"lon": lon_raw, "lat": lat_raw, "value": value_raw})
    return rows, points, skipped


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--csv", help="use a local copy of the source CSV")
    args = parser.parse_args()

    raw, source = read_source(args.csv)
    digest = hashlib.sha256(raw).hexdigest()
    text = raw.decode("utf-8-sig")
    rows, points, skipped = build_points(text)
    if not points:
        raise SystemExit("no valid abundance points found")

    meta = {
        "field": "Herbivores",
        "unit": "individuals per 100 g dry soil",
        "coordinates": ["Pixel_Long", "Pixel_Lat"],
        "pixels": len(points),
        "source_rows": len(rows),
        "skipped_rows": skipped,
        "source": source,
        "source_sha256": digest,
        "download_date": dt.date.today().isoformat(),
        "license": LICENSE,
        "license_url": LICENSE_URL,
        "citation": CITATION,
        "color_transform": "log10(Herbivores + 1)",
    }
    header = (
        "/* Generated by tools/build_abundance.py. Do not edit by hand.\n"
        f" * {CITATION}\n"
        f" * Source SHA-256: {digest}\n"
        " */\n"
    )
    body = (
        header
        + "window.NKU_ABUNDANCE_META = "
        + json.dumps(meta, ensure_ascii=False, separators=(",", ":"))
        + ";\n"
        + "window.NKU_ABUNDANCE = [\n"
        + ",\n".join(
            "  {lon: " + p["lon"] + ", lat: " + p["lat"] + ", value: " + p["value"] + "}"
            for p in points
        )
        + "\n];\n"
    )
    OUT.write_text(body, encoding="utf-8")
    print(
        f"wrote {OUT.relative_to(ROOT)}: {len(points)} points from {len(rows)} rows; "
        f"skipped {sum(skipped.values())} ({skipped}); sha256={digest}"
    )


if __name__ == "__main__":
    try:
        main()
    except (OSError, ValueError, urllib.error.URLError) as exc:
        print(f"build_abundance.py: {exc}", file=sys.stderr)
        raise SystemExit(1)
