#!/usr/bin/env python3
"""Generate js/home-geo.js for the homepage dot maps.

Reads the Natural Earth basemaps already shipped in img/home-maps/ (public
domain, see SOURCES.md) and writes land masks sampled on a lon/lat grid plus a
simplified China outline and the maritime indicator lines. The output contains
geography only - no nematode data. Standard library only.

    python3 tools/build_home_geo.py
"""
import json, math, pathlib, re

ROOT = pathlib.Path(__file__).resolve().parent.parent
MAPS = ROOT / "img" / "home-maps"

def path_d(svg, pid):
    s = (MAPS / svg).read_text(encoding="utf-8")
    return re.search(r'id="' + pid + r'" d="([^"]*)"', s).group(1)

def rings(d, to_lonlat):
    out, cur, x, y = [], None, 0.0, 0.0
    toks = re.findall(r"[MZl]|-?\d*\.?\d+(?:e-?\d+)?", d)
    i, mode = 0, None
    while i < len(toks):
        t = toks[i]
        if t in "MZl":
            mode = t; i += 1
            if t == "Z":
                if cur: out.append(cur); cur = None
            continue
        a, b = float(toks[i]), float(toks[i + 1]); i += 2
        if mode == "M":
            if cur: out.append(cur)
            x, y = a, b; cur = [to_lonlat(x, y)]; mode = "l"
        else:
            x += a; y += b; cur.append(to_lonlat(x, y))
    if cur: out.append(cur)
    return out

def world_ll(x, y): return ((x - 50) / 2.5 - 180, 90 - y / 2.5)
def china_ll(x, y): return ((x - 19.5) / 8.5 + 72, 56 - (y - 12) / 8.5)

def bbox(r):
    xs = [p[0] for p in r]; ys = [p[1] for p in r]
    return min(xs), min(ys), max(xs), max(ys)

def inside(pt, polys):
    x, y = pt; hit = False
    for r, (x0, y0, x1, y1) in polys:
        if x < x0 or x > x1 or y < y0 or y > y1: continue
        n = len(r); j = n - 1
        for k in range(n):
            xi, yi = r[k]; xj, yj = r[j]
            if (yi > y) != (yj > y) and x < (xj - xi) * (y - yi) / (yj - yi) + xi:
                hit = not hit
            j = k
    return hit

def dp(pts, tol):
    if len(pts) < 3: return pts
    a, b = pts[0], pts[-1]
    dx, dy = b[0] - a[0], b[1] - a[1]; L = math.hypot(dx, dy) or 1e-9
    idx, dmax = 0, -1
    for i in range(1, len(pts) - 1):
        p = pts[i]
        d = abs(dy * p[0] - dx * p[1] + b[0] * a[1] - b[1] * a[0]) / L if L > 1e-9 else math.hypot(p[0]-a[0], p[1]-a[1])
        if d > dmax: idx, dmax = i, d
    if dmax > tol:
        return dp(pts[:idx + 1], tol)[:-1] + dp(pts[idx:], tol)
    return [a, b]

def grid_mask(polys, west, north, step, cols, rows):
    """Return rows of run-length strings 'start:len,...' for land cells."""
    out = []
    for r in range(rows):
        lat = north - (r + 0.5) * step
        runs, start = [], None
        for c in range(cols + 1):
            land = c < cols and inside((west + (c + 0.5) * step, lat), polys)
            if land and start is None: start = c
            if not land and start is not None: runs.append(f"{start}:{c - start}"); start = None
        out.append(",".join(runs))
    return out

def main():
    world = [(r, bbox(r)) for r in rings(path_d("world-base.svg", "world-land"), world_ll) if len(r) > 2]
    china_r = [r for r in rings(path_d("china-base.svg", "china-land"), china_ll) if len(r) > 2]
    china = [(r, bbox(r)) for r in china_r]
    mar = rings(path_d("china-base.svg", "china-maritime-indicators"), china_ll)

    W = dict(west=-180, north=84, step=1.8, cols=200, rows=78)   # 84N..56.4S
    world_rows = grid_mask(world, W["west"], W["north"], W["step"], W["cols"], W["rows"])
    # which world cells are China (for the highlighted entry)
    china_cells = []
    for r in range(W["rows"]):
        lat = W["north"] - (r + .5) * W["step"]
        for c in range(W["cols"]):
            lon = W["west"] + (c + .5) * W["step"]
            if 72 < lon < 136 and 3 < lat < 55 and inside((lon, lat), china):
                china_cells.append(r * W["cols"] + c)

    C = dict(west=73, north=54, step=0.8, cols=78, rows=57)       # 73E..135.4E, 54N..8.4N
    china_rows = grid_mask(china, C["west"], C["north"], C["step"], C["cols"], C["rows"])

    outline = []
    for r in china_r:
        x0, y0, x1, y1 = bbox(r)
        big = (x1 - x0) > 1.2 or (y1 - y0) > 1.2
        s = dp(r, 0.06 if big else 0.02)
        if len(s) >= 3:
            outline.append([[round(p[0], 2), round(p[1], 2)] for p in s])
    maritime = [[[round(p[0], 2), round(p[1], 2)] for p in dp(l, 0.02)] for l in mar]

    data = {
        "source": "Natural Earth v5.1.2 (public domain) via img/home-maps; geography only, no scientific data",
        "world": dict(W, rows_mask=world_rows, china=china_cells),
        "china": dict(C, rows_mask=china_rows, outline=outline, maritime=maritime),
    }
    js = "/* generated by tools/build_home_geo.py - geography only (Natural Earth, public domain) */\nwindow.NKU_GEO = " + json.dumps(data, separators=(",", ":")) + ";\n"
    (ROOT / "js" / "home-geo.js").write_text(js, encoding="utf-8")
    print("world land cells:", sum(int(x.split(':')[1]) for row in world_rows for x in row.split(',') if x),
          "china cells:", len(china_cells),
          "china grid land:", sum(int(x.split(':')[1]) for row in china_rows for x in row.split(',') if x),
          "outline pts:", sum(len(r) for r in outline), "bytes:", len(js))

if __name__ == "__main__":
    main()


def build_land():
    """Simplified world land as an SVG path (viewBox 0 0 900 350: lon -180..180, lat 84..-56)."""
    rs = [r for r in rings(path_d("world-base.svg", "world-land"), world_ll) if len(r) > 2]
    parts = []
    for r in rs:
        x0, y0, x1, y1 = bbox(r)
        if y1 < -56: continue
        if (x1 - x0) * (y1 - y0) < 1.2: continue
        s = dp(r, 0.28)
        if len(s) < 4: continue
        pts = [((lon + 180) * 2.5, (84 - max(lat, -56)) * 2.5) for lon, lat in s]
        parts.append("M" + "L".join(f"{x:.1f},{y:.1f}" for x, y in pts) + "Z")
    d = "".join(parts)
    js = "/* generated by tools/build_home_geo.py (build_land) - Natural Earth, public domain */\nwindow.NKU_LAND = " + json.dumps({"viewBox": [0, 0, 900, 350], "d": d}) + ";\n"
    (ROOT / "js" / "home-land.js").write_text(js, encoding="utf-8")
    print("land bytes", len(js))

if __name__ == "__main__":
    build_land()
