#!/usr/bin/env python3
"""Import the verified global Herbivores (plant-feeding nematode) layer.

Writes js/home-abundance.js for the homepage world and China maps.

    python3 tools/import_herbivores.py --csv nematode_aggregated_wCovariateData.csv
    python3 tools/import_herbivores.py --download

Source: van den Hoogen et al. (2020) Scientific Data 7:103, aggregated pixels
(expected about 1,933 rows). Values are individuals per 100 g dry soil; the
maps colour log10(Herbivores + 1) on one shared scale. Nothing is interpolated
or invented: rows without valid coordinates or values are skipped and counted.
"""
import argparse, csv, datetime, hashlib, io, json, math, sys, urllib.request
from pathlib import Path

URL = ("https://raw.githubusercontent.com/hooge104/2020_global_nematode_dataset/"
       "master/data/nematode_aggregated_wCovariateData.csv")
LAT = ("pixel_lat", "latitude", "lat", "y")
LON = ("pixel_long", "pixel_lon", "longitude", "lon", "long", "x")
HERB = ("herbivores", "herbivore")
OUT = Path(__file__).resolve().parents[1] / "js" / "home-abundance.js"


def pick(fields, names):
    low = {f.lower().strip(): f for f in fields}
    for n in names:
        if n in low:
            return low[n]
    return None


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    src = ap.add_mutually_exclusive_group(required=True)
    src.add_argument("--csv", type=Path, help="local copy of the aggregated CSV")
    src.add_argument("--download", action="store_true", help="download the aggregated CSV")
    ap.add_argument("--out", type=Path, default=OUT)
    ap.add_argument("--expect", type=int, default=1933, help="expected pixel count (warning only)")
    args = ap.parse_args()

    raw = urllib.request.urlopen(URL, timeout=60).read() if args.download else args.csv.read_bytes()
    digest = hashlib.sha256(raw).hexdigest()
    rows = list(csv.DictReader(io.StringIO(raw.decode("utf-8-sig"))))
    if not rows:
        sys.exit("No rows found.")
    f_lat, f_lon, f_h = pick(rows[0].keys(), LAT), pick(rows[0].keys(), LON), pick(rows[0].keys(), HERB)
    if not (f_lat and f_lon and f_h):
        sys.exit(f"Missing columns. Found: {', '.join(rows[0].keys())}")

    points, skipped = [], 0
    for r in rows:
        try:
            lat, lon, h = float(r[f_lat]), float(r[f_lon]), float(r[f_h])
        except (TypeError, ValueError):
            skipped += 1
            continue
        if not (-90 <= lat <= 90 and -180 <= lon <= 180) or h < 0 or math.isnan(h):
            skipped += 1
            continue
        points.append([round(lon, 3), round(lat, 3), round(h, 2)])
    if not points:
        sys.exit("No valid points.")
    logs = sorted(math.log10(p[2] + 1) for p in points)
    p99 = logs[min(len(logs) - 1, int(round(0.99 * (len(logs) - 1))))]
    if len(points) != args.expect:
        print(f"warning: {len(points)} valid pixels, expected about {args.expect}", file=sys.stderr)

    payload = {
        "status": "imported",
        "source": "van den Hoogen et al. (2020) Scientific Data 7:103; aggregated pixels",
        "url": URL if args.download else str(args.csv.name),
        "field": f_h, "unit": "individuals per 100 g dry soil", "transform": "log10(x + 1)",
        "retrieved": datetime.date.today().isoformat(), "sha256": digest,
        "count": len(points), "skipped": skipped,
        "domain": [round(logs[0], 4), round(p99, 4)],
        "points": points,
    }
    args.out.write_text(
        "/* Generated by tools/import_herbivores.py. Do not edit by hand. */\n"
        "window.NKUHomeAbundance = " + json.dumps(payload, separators=(",", ":")) + ";\n",
        encoding="utf-8")
    print(f"wrote {args.out} · {len(points)} points · skipped {skipped} · domain {payload['domain']}")


if __name__ == "__main__":
    main()
